/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xm_study_ndk_JniText */

#ifndef _Included_com_xm_study_ndk_JniText
#define _Included_com_xm_study_ndk_JniText
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
